<?php

namespace AppBundle\Repository;

/**
 * ReportesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportesRepository extends \Doctrine\ORM\EntityRepository
{
}
